steps:
  - name: python:3.6-buster
    id: Python Env Setup And App Tests
    entrypoint: bash
    dir: /workspace
    args:
    - -c
    - |
      date
      echo "Loading Pattern Library Templates"
      ./scripts/load_templates.sh
      date
      echo "Pip Install"
      date
      pip install pipenv
      date
      echo "PipEnv Install"
      pipenv install --dev --deploy
      date
      echo "Run Tests"
      pipenv run pytest tests/unit --ignore=node_modules -n 4

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    id: Docker Build
    args: [ 'build', '-t', 'europe-west2-docker.pkg.dev/ons-ci-int/int-docker-snapshot/rh-ui:$BRANCH_NAME', '-f', 'Dockerfile', '.' ]
      
timeout: '2400s'
images: [ 'europe-west2-docker.pkg.dev/ons-ci-int/int-docker-snapshot/rh-ui:$BRANCH_NAME' ]




