steps:
  # Grab cached M2 repo
#  - name: gcr.io/cloud-builders/gsutil
#    id: Get M2 Cache
#    args: ['cp', 'gs://ons-ci-int-cloudbuild-maven-cache/m2.tar.gz', 'm2.tar.gz']
#      #
#  # See https://github.com/GoogleCloudPlatform/cloud-builders-community to get the tar command
#  - name: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-ci/cloudbuild/tar
#    id: Expand M2 Cache
#    args: ['xpzf', 'm2.tar.gz']
steps:
  - name: python
    id: Load Pattern Library Templates
    entrypoint: bash
    dir: /workspace
    args:
    - -c
    - |
      ./scripts.load_templates.sh

  # Install dependencies
  - name: python
    id: Pip setup
    entrypoint: pip
    args: ["install", "--dev", "--deploy"]

  # Run unit tests
  - name: python
    id: Run Python Unit Tests
    entrypoint: python
    args: ["-m", "pytest", "tests/unit", "--cov=app", "--cov-report xml", "--ignore=node_modules"] 

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    id: Docker Build
    args: [ 'build', '-t', 'europe-west2-docker.pkg.dev/ons-ci-int/int-docker-snapshot/rh-ui:$BRANCH_NAME', '-f', 'Dockerfile', '.' ]
      
#  - name: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-ci/cloudbuild/tar
#    id: Compress M2 Cache
#    args: ['cpzf', 'm2.tar.gz', '.m2']
#
#  - name: gcr.io/cloud-builders/gsutil
#    id: Save M2 Cache
#    args: ['cp', 'm2.tar.gz', 'gs://ons-ci-int-cloudbuild-maven-cache/m2.tar.gz']


images: [ 'europe-west2-docker.pkg.dev/ons-ci-int/int-docker-snapshot/rh-ui:$BRANCH_NAME' ]




