steps:
  - name: python:3.10.4-buster
    id: Python Env Setup And App Tests
    entrypoint: bash
    dir: /workspace
    args:
    - -c
    - |
      date
      echo "Loading Pattern Library Templates"
      ./scripts/load_templates.sh
      date
      echo "Pip Install"
      date
      pip install pipenv
      date
      echo "PipEnv Install"
      pipenv install --dev --deploy
      date
      echo "Run Tests"
      pipenv run pytest tests/unit --ignore=node_modules -n 2

timeout: '2400s'




