version: '3.8'
services:

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  mock-service:
    container_name: mock-service
    image: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-release/mock-service:latest
    ports:
      - "8162:8162"

  rh-ui:
    container_name: rh-ui
    image: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-release/rh-ui:latest
    depends_on:
      - redis
      - mock-service
    environment:
      - REDIS_SERVER=redis
      - REDIS_PORT=6379
      - APP_SETTINGS=DevelopmentConfig
      - PORT=9092
      - RHSVC_URL=http://host.docker.internal:8071
    ports:
      - "9092:9092"
