#
# This file is a placeholder for a docker compose file that will start the rh-ui.
#

version: '3.8'
services:
  rh-ui:
    container_name: rh-ui
    image: rh-ui
    depends_on:
      - redis
    environment:
      - REDIS_SERVER=redis
      - REDIS_PORT=6379
      - APP_SETTINGS=DevelopmentConfig
      - PORT=9092
      - ADDRESS_INDEX_SVC_URL=http://localhost:8162
      - RHSVC_URL=http://host.docker.internal:8071
    ports:
      - "9092:9092"
